### PR TITLE
feat: add docs to navbar

### PR DESCRIPTION
**Pull request by AtulPant2704**
- Add docs to navbar
- CSB Link:- https://snw46.csb.app/components/Navbar/navbar.html

> Hamburger is not active as of now, I will work on it in the end

### CODE REVIEW

**Review by Abhijeet43 — APPROVED** [review]
The code looks good!!!

**Comment by Abhijeet43** [comment]
> * Add docs to navbar
> * CSB Link:- https://snw46.csb.app/components/Navbar/navbar.html
> 
> > Hamburger is not active as of now, I will work on it in the end
Hey @AtulPant2704 just a suggestion... Please try to subtle down shadow a bit.. At times feels really heavy

**Review by Abhijeet43 — COMMENTED** [review]
Just a suggestion: Hey @AtulPant2704  try to subtle down shadow a bit .... At times it looks heavy

**Review by Sudhanshusoni45 — APPROVED** [review]
Looks good to Go!

**Pull request merged**
