### PR TITLE
feat: add card component

### PR DESCRIPTION
**Pull request by AtulPant2704**
This is just the layout of the cards, colors, font-size, font-style and spacing will vary in the Component Library.

### CODE REVIEW

**Comment by Kevin-Solomon** [comment]
Just a suggestion, it would be great if you add screenshots of the components.

**Comment by mohammed-sas** [comment]
hey , just a suggetion ,it would be better if you change the css for horizontal card since it looks like vertical card to me

**Comment by AtulPant2704** [comment]
CodeSandbox link:-
https://wgv4t.csb.app/components/Card/card.html

**Review by mohammed-sas — APPROVED** [review]
your code is good to merge

**Comment by Kevin-Solomon** [comment]
> CodeSandbox link:- https://wgv4t.csb.app/components/Card/card.html

Looks great , Atul !!

**Review by Kevin-Solomon — APPROVED** [review]

**Review by AnkurChunekar — APPROVED** [review]

**Pull request merged**
